color palettes:
  main: https://colorpalettes.net
  selected:
    - https://colorpalettes.net/color-palette-4045/
    - https://colorpalettes.net/color-palette-2271/
    - https://colorpalettes.net/color-palette-3852/
    - https://colorpalettes.net/color-palette-1914/