name: Build LaTeX document
on: 
    push:
        branches: github-actions
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src

      # - name: Test previous commit
      #   run: |
      #     git log -1
      #     echo "Show the files in the src directory"
      #     ls -la src
      #     echo "Show the files in the LaTeX directory"
      #     ls -la src/LaTeX
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src/LaTeX
          root_file: mwe.tex
          extra_system_packages: "inkscape"
          latexmk_shell_escape: True
      - name: Show files in dir
        run: |
          echo "Show the files in the LaTeX directory"
          ls -la src/LaTeX
      - name: Release PDF
        uses: softprops/action-gh-release@v2
        with:
          files: src/LaTeX/mwe.pdf
          